### PR TITLE
Handle jest suites that failed to run

### LINKED ISSUE #12: Test suite failures are not reported
Hi,
We switched to this library from `jest-teamcity-reporter`, and noticed that general test suite failures are not being reported.
The other library indeed reports them as a "fake" test: https://github.com/winterbe/jest-teamcity-reporter/blob/2ebc892673611123abe34328a97a37900e277092/index.js#L25

I believe something similar should be done here.
I won't have time this week to submit a PR, so I'm opening this issue in case someone else wants to take it.
Thanks!

### PR DESCRIPTION
**Pull request by yurynix**
Hello 👋 

If jest fails to run a spec file, it will populate `testExecError` and `testResults` will be an empty array.
Currently `jest-teamcity` doesn't handle that, so TC's overview will not report anything regarding the failure, just `exit code 1`

See `buildFailureTestResult`:
https://github.com/facebook/jest/blob/93cde55bf1d770bf2f4e386024032298535a65ea/packages/jest-test-result/src/helpers.ts#L76-L78

Unfortunately, it seems that TeamCtiy doesn't support "failing" on a test suite level: 
https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000531484-Fail-TestSuite-without-failing-TestCase

So, in this PR, I push a "fake" test result that will bring the error message to the TC overview tab.

### CODE REVIEW

**Review by itereshchenkov — APPROVED** [review]
Good catch 👍 Thanks for your contribution!

**Comment by yurynix** [comment]
@itereshchenkov Not to rush you or anything, when you're planning to release a new version to npm? 🙂

**Comment by itereshchenkov** [comment]
> @itereshchenkov Not to rush you or anything, when you're planning to release a new version to npm? 🙂

I will try to do it today

**Comment by itereshchenkov** [comment]
> @itereshchenkov Not to rush you or anything, when you're planning to release a new version to npm? 🙂

The new version was published. Please feel free to update it

**Comment by yurynix** [comment]
Thank you @itereshchenkov ! 🙇

**Comment by scinos** [comment]
This is still broken, as it won't report suites as failed if an `after` hook failed. I raised #24 to fix it.

**Pull request merged**
